### ISSUE TITLE
Can't install on Laravel 4.2

### ISSUE THREAD

**Issue by rombat** [adamwathan/eloquent-oauth-l4#1]
Hi,
Here's the error message when I try `composer require adamwathan/eloquent-oauth-l4`

```
[InvalidArgumentException]
  Could not find package adamwathan/eloquent-oauth-l4 at any version for your minimum-stability (dev). Check the package spelling or your minimum-stability
```

**Comment by adamwathan** [comment]
Whoops! Looks like I never pushed it to Packagist.

Added it and added a tag for 0.1.0, should hopefully work for you now!

**Comment by SivaRamRIT** [comment]
I am having the same problem. I tried every version of .0*

```
- adamwathan/eloquent-oauth-l4 v0.2.0 requires guzzlehttp/guzzle ^6.0 -> no
```

matching package found.
    - adamwathan/eloquent-oauth-l4 v0.1.2 requires guzzlehttp/guzzle ~5.0 -> no
matching package found.
    - adamwathan/eloquent-oauth-l4 v0.1.1 requires adamwathan/eloquent-oauth dev
-master -> no matching package found.
    - adamwathan/eloquent-oauth-l4 v0.1.0 requires adamwathan/eloquent-oauth dev
-master -> no matching package found.
    - Installation request for adamwathan/eloquent-oauth-l4 \* -> satisfiable by
adamwathan/eloquent-oauth-l4[v0.1.0, v0.1.1, v0.1.2, v0.2.0].

**Comment by adamwathan** [comment]
Huh, I was able to install it on a new project just now with no issues. Can you list your `composer.json`? It seems weird that it wouldn't be able to find Guzzle...

**Comment by SivaRamRIT** [comment]
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "require": {
        "laravel/framework": "4.2._",
        "aws/aws-sdk-php-laravel": "1._",
                "guzzlehttp/guzzle": "~4.0",
        "facebook/php-sdk-v4" : "4.0._",
        "pda/pheanstalk": "~2.0",
        "kumar/sesmailer": "0.1._",
        "kumar/nexmo": "0.2._",
        "maatwebsite/excel": "1._",
        "bugsnag/bugsnag-laravel": "1._",
        "adamwathan/eloquent-oauth-l4": "0._"

```
},
"require-dev": {
     "way/generators": "2.*",
     "mustache/mustache": "~2.6",
     "phpunit/phpunit": "4.2.*",
     "mockery/mockery": "0.9.1",
     "phpspec/phpspec": "~2.0"
},
"autoload": {
    "classmap": [
        "app/controllers",
        "app/models",
        "app/utilities",
        "app/database/migrations",
        "app/database/seeds",
        "app/tests/TestCase.php"
    ],
    "psr-4":{
        "CausBuzz\\":"app/CausBuzz"
    }
},
"scripts": {
    "post-install-cmd": [
        "php artisan clear-compiled",
        "php artisan optimize"
    ],
    "post-update-cmd": [
        "php artisan clear-compiled",
        "php artisan optimize"
    ],
    "post-create-project-cmd": [
        "php artisan key:generate"
    ]
},
"config": {
    "preferred-install": "dist"
},
"minimum-stability": "stable"
```

}

**Comment by adamwathan** [comment]
Ah you are using Guzzle ~4.0 already and this package requires Guzzle 6 :( You will have to update whatever it is that is using Guzzle 4 to Guzzle 6 before you can bring this package in. Guzzle is a really annoying dependency to manage because so many packages rely on different versions of it. I try to keep up with the latest version so I'm at least not the reason holding someone back from using some other new package :/ Not sure of a better solution.

**Comment by SivaRamRIT** [comment]
will try that, thanks
