### ISSUE TITLE
Different approach to save data from FB

### ISSUE THREAD

**Issue by fari-99** [adamwathan/eloquent-oauth-l4#5]
Hello, I want to ask something about this function

``` php
OAuth::login('facebook', function($user, $details){
//$user->name = $details->nickname;
});
```

can i change it the `$user` to `$user_1` where

``` php
$user_1 =  array(
    'name' => ''
);
OAuth::login('facebook', function($user_1, $details){
//$user_1->name = $details->nickname;
});
```

Because I want to login fb in 'front' page and pass the data to server using guzzlehttp.

**Comment by adamwathan** [comment]
I'm not sure exactly what you are asking, but the `$user` parameter is passed in from within the package so you can't change what it references. If you need access to `$user_1` inside the closure, you can `use` that variable, like so:

``` php
$user_1 =  array(
    'name' => ''
);
OAuth::login('facebook', function ($user, $details) use ($user_1) {
//$user_1->name = $details->nickname;
});
```

**Comment by fari-99** [comment]
thanks for fast respond, i will try it.

**Comment by fari-99** [comment]
I'm sorry for my explanation about my problem earlier.
here what i mean,
1. Login FB via web_front (there is no database here)
2. Pass the data OAuth::Login $user to the web_server (the database is here) using GuzzleHTTP
3. Authenticate in server

I already using the Login FB, but i have to redirect to server, save and authenticate in there, but after that i can't go back to web_front. so maybe i try creating some variabel like `$user_1`, but because there is no database in web_front, i always get error about the database. haha.

i just can create database for web_front to temporary save data OAuth::login, and pass the data in database temp to server, and then clear it, but i just can't. haha. maybe i'm just lazy af.

**Comment by fari-99** [comment]
Hello, i want to tell you that i already solved my problem

here's my code in controller web_front

``` php
     try {
        OAuth::login('facebook', function($user, $details){
            $client = new GuzzleHttp\Client();
            $response = $client->request('POST', 'localhost:8080/facebook/loginBro', array(
                    'form_params' => array(
                        'email' => $details->email,
                        'nickname' => $details->nickname,
                        'name' => $details->full_name,
                        'profile_image' => $details->avatar
                    )
                ));
            echo "body = " . $response->getBody();
        });
    } catch (ApplicationRejectedException $e) {
        // User rejected application
    } catch (InvalidAuthorizationCodeException $e) {
        // Authorization was attempted with invalid
        // code,likely forgery attempt
    }
```

here's my route in web_server

``` php
Route::post('facebook/loginBro', function(){
    return Input::all();
});
```

but, you must create database temporary in web_front. haha
